
apiVersion: batch/v1
kind: Job
metadata:
  name: inject-lags-indexes
  namespace: ibm-aiops-installer
spec:
  serviceAccountName: demo-admin
  template:
    spec:
      containers:
        - name: load
          image: quay.io/niklaushirt/ibm-aiops-tools:2.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

              echo "*****************************************************************************************************************************"
              echo " ✅ STARTING: Load log anomaly Golden Signals training files"
              echo "*****************************************************************************************************************************"

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    📥 Downloading log anomaly training files"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              export TRAINING_REPO=https://github.com/niklaushirt/ibm-aiops-trainingdata.git
              git clone $TRAINING_REPO
              cd ibm-aiops-trainingdata

              echo ""
              echo ""
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "   🔎 This Repo includes those latestet Commits"
              git log|head -n 17
              echo ""
              echo ""

              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 Starting Data Load"
              echo "   ------------------------------------------------------------------------------------------------------------------------------"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              echo "This Repo includes those latestet Commits"
              echo "------------------------------------------------------------------------------------------------------------------------------"
              git log|head -n 17
              echo ""
              echo ""

              ./training/load-gs-logs-kafka_date.sh

              echo "*****************************************************************************************************************************"
              echo " ✅ DONE"
              echo "*****************************************************************************************************************************"
              while true
              do
                sleep 1000
              done
          env:
            - name: INDEX_OVERWRITE
              value : "true"
            - name: VERSION
              value : "latest"
      restartPolicy: Never

  backoffLimit: 500
