

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing IBM AIOps
#
#  IBM AIOps
#
#  ©2024 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
#  - Turbonomic Demo Content
#     - Demo User
#     - RobotShop Demo App with synthetic metric
#     - Instana target (if Instana is installed - you have to enter the API Token Manually)
#     - Groups for vCenter and RobotShop
#     - Groups for licensing
#     - Resource Hogs
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: 🟣🟣🟣 INSTALLATION MODULE START - {{current_ibmaiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      🟡🟡🟡🟡🟡  🚀 IBM AIOps - INSTALLING {{current_ibmaiops_feature.kind}} 🟡🟡🟡🟡🟡                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"

- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export AIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $AIOPS_NAMESPACE-demo-ui ibm-aiops-demo-ui  -o jsonpath="{['spec']['host']}")|| true
    OPENSHIFT_ROUTE=$(oc get route -n openshift-console console -o jsonpath={.spec.host})    

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: ibm-aiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerBottom")}}
      text: 'Installing  {{current_ibmaiops_feature.kind}} - '    
      link:
          href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-aiops-installer/pods/$INSTALL_POD/logs"
          text: Open Logs  
    EOF
  ignore_errors: true
  args:
    executable: /bin/bash

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Login
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name:   🚀 INITIALIZATION - Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


- name:   🚀 INITIALIZATION - Check Cluster Connectivity
  fail: msg="You must be logged in to the server!"
  when: CLUSTER_NAME.stdout==""




- name: 🟣 Installing {{current_ibmaiops_feature.kind}} with the following configuration
  debug:
    var: current_ibmaiops_feature
    verbosity: 1





# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Encrypted Licenses
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: Get Licenses 
  block:
  - name: 💾 SET Turbo License from Config File - {{current_ibmaiops_feature.turbo_license | default("NONE")}} 
    set_fact: current_turbo_license={{current_ibmaiops_feature.turbo_license| default("NONE")}}


- name: Get Licenses from Env Variable
  block:
    - name: 💾 SET Turbo License from Env Variable - {{ lookup('ansible.builtin.env', 'TURBO_LICENSE', default='NONE') }}
      set_fact: current_turbo_license={{ lookup('ansible.builtin.env', 'TURBO_LICENSE', default='NONE') }}
  when: current_turbo_license == "NONE" 


- name: Decrypt Licenses 
  block:
  - name: Create Token File
    shell: |
      echo {{global_config.license_token}} > /tmp/pwd.yaml
    ignore_errors: true


  - name: Get License from Vault
    shell: |
      OS=$(uname -s | tr '[:upper:]' '[:lower:]')
      if [ "${OS}" == "darwin" ]; then
            echo "MAC"
            LICENSE_FILE=$(pwd)"/roles/ibm-aiops-turbonomic-demo-content/vars/lic.yaml"
      else
            LICENSE_FILE="{{role_path}}/vars/lic.yaml"
      fi    
      echo $LICENSE_FILE
      ansible-vault decrypt --vault-password-file /tmp/pwd.yaml --output /tmp/license.yaml "$LICENSE_FILE"
    ignore_errors: true

  - name: Include License from Vault
    ansible.builtin.include_vars:
      file: /tmp/license.yaml
      name: licenses
    ignore_errors: true

  - name: Cleanup
    shell: |
      rm /tmp/pwd.yaml
      rm /tmp/license.yaml
    ignore_errors: true

  - name: 💾 SET Turbo License from Vault
    set_fact: current_turbo_license={{licenses.turbo_license }} 
  when: global_config.license_token is defined 




- name:  🟣 Check Turbo License"
  debug:
    msg:
    - "** Missing License Information ***********************************************************************"
    - " Turbo License:      {{ current_turbo_license}}"
    - " ❌ Most of the customization won't work...."
    - ""
  when: current_turbo_license == "NONE"


- name:  🟣 Check Sales and Agent Key
  fail: msg="❌ Missing License Information - Aborting"
  when: current_turbo_license == "NONE"



- name:  🟢 Turbo License - OK"
  debug:
    msg:
    - "** License Information ***********************************************************************"
    - " Turbo License:      {{ current_turbo_license}}"
    - " ✅ OK...."
    - ""
    verbosity: 2
  when: current_turbo_license != "NONE"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: 📥 Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: 📥 Init Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/01_init-logging.yaml"

  
# Start block
- name: 📥 Start Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL TURBONOMIC DEMO CONTENT
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install TURBONOMIC
- name: 📥 Install Turbonomic
  include_tasks: 10_addons-turbonomic-demo-content.yaml


# Update IBMAIOps Cards
- name: 📥 Update IBMAIOps Cards
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/99_update_cards.yaml"





- name: 📥 End Logging
  include_tasks: "{{role_path}}/../ibm-aiops-global/tasks/91-log-end.yaml"




- name: ✅ INSTALLATION MODULE DONE - {{current_ibmaiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ✅ IBM AIOps - DONE INSTALLING {{current_ibmaiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
