{
 "title": "Application Carbon Footprint - Private Cloud - NIK",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DATACENTER",
    "label": "Data Center",
    "query": "select\n    CONCAT(name, ' - ', oid) AS __text,\n    oid AS __value\nfrom entity\nwhere\n    type = 'DATACENTER'\n    --and attrs->>'targets' like '%vCenter%'\n    and last_seen > now()\norder by 1"
   },
   { "name": "INCLUDE_GROUPS", "label": "Include Groups", "query": "Yes, No" },
   {
    "name": "APPLICATION",
    "label": "Application(s)",
    "query": "select\n    CONCAT(e.name, ' - ', e.type, ' (', e.oid, ')') AS __text,\n    e.oid AS __value\nfrom entity e\njoin scope s on e.oid = s.scoped_oid and s.seed_oid IN (${DATACENTER})\nwhere\n    ((e.type = 'GROUP' AND e.attrs->'member_types' ? 'VIRTUAL_MACHINE' AND '${INCLUDE_GROUPS}')\n    OR (e.type = 'BUSINESS_APPLICATION'))\n    and last_seen > now()\norder by 1"
   },
   {
    "name": "VM_ENERGY_LIST",
    "query": "SELECT\n  distinct e.oid\nFROM entity e\nWHERE\n  (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo()) AND\n  e.type = 'VIRTUAL_MACHINE' AND\n  e.environment = 'ON_PREM'"
   },
   {
    "name": "VM_LIST",
    "label": "Virtual Machine(s)",
    "query": "SELECT\n    concat(e.name, ' (', e.oid, ')') AS __text,\n    e.oid AS __value\nFROM entity e\njoin scope s on e.oid = s.scoped_oid and s.scoped_type = 'VIRTUAL_MACHINE' AND s.seed_oid IN (${APPLICATION})\nWHERE\n  (e.first_seen, e.last_seen) OVERLAPS ($__timeFrom(), $__timeTo()) AND\n  e.type = 'VIRTUAL_MACHINE' AND\n  e.oid IN (${VM_ENERGY_LIST})\nORDER BY e.name"
   },
   { "name": "PRIVATE_CLOUD_AVG_PUE", "label": "PUE", "query": "1.67" },
   { "name": "PRIVATE_CLOUD_EMISSIONS_FACTOR", "label": "Emissions Factor", "query": "0.000709" }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Me",
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "options": {
      "content": "# **Applications Carbon Footprint - Private Cloud**\n***\n## **Summary**\nThis dashboard shows the impact of IBM Turbonomic application resource manager on Energy consumption and Carbon Footprint in your private cloud data center environment. \n\nThis dashboard focuses on the calculated Energy and Carbon Footprint data for Virtual Machines (VMs) running in a vSphere environment and includes Energy consumption and Carbon Footprint emissions for VMs, optimization opportunities and their associated net impact on resources, as well as a table comparison of Carbon Footprint across VM groups and Business Applications (see \"Top Applications by CO2e Emissions\" section).\n***\n\n## **Data and Methodology**\n---\n### Energy (Wh) \nVirtual Machine (VM) Energy consumption data is being calculated for individual VM based on the distribution of Host's power data among the VMs running on it. The following methodology is used to quantify Energy consumption for VMs:\n\nConsider the following notation:\n\n**n** - Number of VMs deployed on a Host\\\n**VM_i** - The i-th VM deployed on a Host\\\n**vCPU_i** - The number of vCPUs allocated to  VM~i~ \\\n**P** - Total power consumed by the Host\\\n**U** - Total CPU utilization at the Host (due to hypervisor, OSs, and applications running on all the VMs) \\\n**u_i** - CPU utilization of VM~i~ \\\n**P_idle** - is the power consumed by the Host during active idle state when no process is actively executing \\\n**P_overhead** - is the power consumed due to the hypervisor or other processes that are not specific to any single VM\\\n**P_active** - is the power consumed by the OSs and user processes executing on the VMs \\ \n\n**Host power can be divided into 3 components:**\n\n    P = P_idle + P_overhead + P_active\n\n**The instantaneous power at or over a time interval t for VM_i is then determined as follows:**\n\n    P_VM_i = [(vCPU_i / ∑_(k=1)^n {vCPU_k}) * (P_idle + P_overhead)] + [(u_i / ∑_(k=1)^n {u_k}) * P_active]\n\n\n**Splitting total power into idle, overhead, and active components:** \n\nThe idle power of a Host is determined by fitting a model between the total host utilization U and host power P time series. \n\nThe overhead power P_overhead is given by the power consumption at overhead utilization less P_idle, given by [U - (∑_k{u_k})] . \n\nThat is - **P_overhead** = P * [U - (∑_k{u_k})] - P_idle.\n\n\nFollowing the aforementioned methodology we are able to calculate Power consumption for each individual VM that is running on a Host with available Power data. Then, we are converting Power data into Energy data and showing Energy in Wh units in the \"Energy Consumption (Wh)\" graphs. \n\n---\n### CO2e emissions (t)\nCalculations for Carbon Dioxide equivalents (CO2e in metric tons) emissions are made following an open source methodology outlined in Cloud Carbon Footprint website - [www.cloudcarbonfootprint.org](https://www.cloudcarbonfootprint.org/).\\\nSpecifically, in this dashboard CO2e are calculated using the following formula:\n\n    Operational Emissions = CO2e (t) = (energy consumption [Wh]) x [(private cloud average PUE) x (private cloud emissions factor) / 1000]\n\nWhere:\n\n- ***Private Cloud Power Usage Effectiveness (PUE)*** = An average PUE of 1.67 is used in our calculations. This [451 report](https://d39w7f4ix9f5s9.cloudfront.net/e3/79/42bf75c94c279c67d777f002051f/carbon-reduction-opportunity-of-moving-to-aws.pdf) notes: \"Adding it all up, the power usage effectiveness (PUE, the ratio of total datacenter power and the IT power) ranged from 1.63 to 1.70 in the survey sample and was consistent across company sizes. This is in line with broader industry data collected by the Uptime Institute but well below the efficiency of AWS operations.\" - 451 Research Report. We use the average of 1.63 and 1.70, which is 1.67.\n\n- ***Private Cloud Emissions Factor*** = `1,562.4 lbs CO2/MWh × (4.536 × 10^(-4) metric tons/lb) × 0.001 MWh/kWh = 7.09 × 10^(-4) metric tons CO2/kWh`. We are using `0.000709` (rounded) in our calculations. ***Note:*** Emission equivalents vary slightly vs. EPA calculation because we are using the rounded numbers of the emissions factor (7.09x10^(-4)).\n\n---\n### Graphs and dashboard functionality\n\n- **Top Applications by CO2e emissions** - this table shows the total CO2e emissions over the chosen dashboard period for groups of VMs that are manually created by end users in Turbonomic as well as total CO2e emissions over the chosen dashboard period for VMs within Business Applications groups that are discovred by APM targets added to Turbonomic such as Dynatrace, AppDynamics, Instana, etc.\n\n- **Total Number of VMs** - this graph shows the total number of VMs, both active and idle, discovered by Turbonomnic. \n\n- **Current Number of Resize Actions** - this graph shows the total number VM optimization opportunities, also know as pending VM Resize actions in Turbonomic.\n\n- **VM Resize Actions Impact on VCPU** - this graph shows the net impact on VCPU resources from all the pending VM Resize actions in Turbonomic. \n\n- **VM Resize Actions Impact on VMem** - this graph shows the net impact on VMEM resources from all the pending VM Resize actions in Turbonomic. \n\n- **Global** and **Scoped Information** sections:\n    - **Global** - this section includes inforamation of the global environment over the selected period of time\n    - **Scoped Information** - this section shows information of the scoped environment which can be controlled by the dashboard's top scope selectors such as \"Data Center\" , \"Application(s)\", and \"Virtual Machine(s)\". For each scope selector, one or multiple entries may be selected. \n\n- **PUE** and **Emissions Factor** - these parameters can be adjusted by the user of this dashboard and impact the calculated CO2e in various graphs of this dashboard. See \"CO2e emissions (t)\" section.\n\n\n"
     }
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Number of VMs",
   "type": "stat",
   "description": "This shows the latest data point for the total number of VMs in the selected scope.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  count(m.current)\nFROM metric m\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_oid IN (${VM_ENERGY_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Current Number of Resize Actions",
   "type": "stat",
   "description": "Current number of pending VM Resize actions. ",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM pending_action a\nwhere\na.type = 'RESIZE' AND\na.target_entity_id IN (${VM_ENERGY_LIST})"
    }
   ]
  },
  {
   "title": "VM Resize Actions Impact on VCPU",
   "type": "stat",
   "description": "Net impact on vCPU resources from pending VM Resize Actions.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\"\r\nFROM pending_action a\r\nwhere\r\n  a.target_entity_id IN (${VM_ENERGY_LIST}) AND\r\n  a.\"type\" = 'RESIZE' AND\r\n  a.description like '%VCPU%' AND a.description not like '%limit%'\r\n"
    }
   ]
  },
  {
   "title": "VM Resize Actions Impact on VMem",
   "type": "stat",
   "description": "Net impact on vMem resources from pending VM Resize Actions.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\"\r\nFROM pending_action a\r\nwhere\r\n  a.target_entity_id IN (${VM_ENERGY_LIST}) AND\r\n  a.\"type\" = 'RESIZE' AND\r\n  a.description like '%VMem%'"
    }
   ]
  },
  {
   "title": "Top Applications by CO2e emissions",
   "type": "table",
   "description": "List of all applications in the selected scope sorted by the ones with the most carbon emissions over the selected period at the top. Carbon emissions associated with application groups are of the VMs that are part of each application group. ",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(eapp.name, ' (', eapp.oid,')') as \"Application Name\",\n  eapp.oid as \"Application OID\",\n  s.scoped_oid as \"VM OID\",\n  eapp.type as \"Grouping Type\"\nFROM scope s\njoin entity eapp on eapp.oid = s.seed_oid\nwhere\n  s.scoped_type = 'VIRTUAL_MACHINE'\n  AND s.finish > now()\n  AND eapp.last_seen > now()\n  AND ((eapp.type = 'GROUP' AND eapp.attrs->'member_types' ? 'VIRTUAL_MACHINE' AND '${INCLUDE_GROUPS}') OR (eapp.type = 'BUSINESS_APPLICATION'))\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  --mvm.time as \"Time\",\n  mvm.entity_oid as \"VM OID\",\n  sum(mvm.current)*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000 as \"CO2e (t)\"\nFROM metric mvm\nwhere \n  $__timeFilter(mvm.time) AND\n  mvm.entity_oid IN (${VM_ENERGY_LIST}) AND\n  mvm.entity_type = 'VIRTUAL_MACHINE' AND\n  mvm.type = 'VCPU'\nGROUP BY \"VM OID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Energy Consumption (Wh) - All VMs",
   "type": "timeseries",
   "description": "Shows the total energy consumption in Wh for VMs in the selected scope and over the selected time period. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)\nFROM metric m\n--JOIN entity e on m.entity_oid = e.\"oid\" AND e.environment = 'ON_PREM' AND e.type = 'VIRTUAL_MACHINE' and m.entity_type = e.type\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_oid IN (${VM_ENERGY_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Carbon Footprint CO2e (t) - All VMs",
   "type": "timeseries",
   "description": "Shows the total carbon footprint in tons of CO2e emissions for VMs in the selected scope and over the selected time period. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000 as \"CO2e (t)\"\nFROM metric m\n--JOIN entity e on m.entity_oid = e.\"oid\" AND e.environment = 'ON_PREM' AND e.type = 'VIRTUAL_MACHINE' and m.entity_type = e.type\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_oid IN (${VM_ENERGY_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  },
  { "title": "Scoped Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Number of VMs",
   "type": "stat",
   "description": "This shows the latest data point for the total number of VMs in the selected scope.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  count(m.current)\nFROM metric m\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_oid IN (${VM_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Current Number of Resize Actions",
   "type": "stat",
   "description": "Current Number of pending VM Resize Actions for all the VMs in the selected scope.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM pending_action a\nwhere\na.type = 'RESIZE' AND\na.target_entity_id IN (${VM_LIST})"
    }
   ]
  },
  {
   "title": "VM Resize Action Impact on VCPU",
   "type": "stat",
   "description": "Net impact on vCPU resources from pending VM Resize Actions in the selected scope.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (a.attrs->'resizeInfo'->'VCPU'->>'to')::float - (a.attrs->'resizeInfo'->'VCPU'->>'from')::float as \"Difference\"\r\nFROM pending_action a\r\nwhere\r\n  a.target_entity_id IN (${VM_LIST}) AND\r\n  a.\"type\" = 'RESIZE' AND\r\n  a.description like '%VCPU%' AND a.description not like '%limit%'\r\n"
    }
   ]
  },
  {
   "title": "VM Resize Action Impact on VMem",
   "type": "stat",
   "description": "Net impact on vMem resources from pending VM Resize Actions in the selected scope.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (a.attrs->'resizeInfo'->'VMEM'->>'to')::float - (a.attrs->'resizeInfo'->'VMEM'->>'from')::float as \"Difference\"\r\nFROM pending_action a\r\nwhere\r\n  a.target_entity_id IN (${VM_LIST}) AND\r\n  a.\"type\" = 'RESIZE' AND\r\n  a.description like '%VMem%'"
    }
   ]
  },
  {
   "title": "Top Applications by CO2e emissions",
   "type": "table",
   "description": "List of all applications in the selected scope sorted by the ones with the most carbon emissions over the selected period at the top. Carbon emissions associated with application groups are of the VMs that are part of each application group. ",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(eapp.name, ' (', eapp.oid,')') as \"Application Name\",\n  eapp.oid as \"Application OID\",\n  s.scoped_oid as \"VM OID\",\n  eapp.type as \"Grouping Type\"\nFROM scope s\njoin entity eapp on eapp.oid = s.seed_oid AND s.seed_oid IN (${APPLICATION})\nwhere\n  s.scoped_type = 'VIRTUAL_MACHINE'\n  AND s.finish > now()\n  AND eapp.last_seen > now()\n  AND ((eapp.type = 'GROUP' AND eapp.attrs->'member_types' ? 'VIRTUAL_MACHINE' AND '${INCLUDE_GROUPS}') OR (eapp.type = 'BUSINESS_APPLICATION'))\n  AND s.scoped_oid IN (${VM_LIST})\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  --mvm.time as \"Time\",\n  mvm.entity_oid as \"VM OID\",\n  sum(mvm.current)*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000 as \"CO2e (t)\"\nFROM metric mvm\nwhere \n  $__timeFilter(mvm.time) AND\n  mvm.entity_oid IN (${VM_LIST}) AND\n  mvm.entity_type = 'VIRTUAL_MACHINE' AND\n  mvm.type = 'VCPU'\nGROUP BY \"VM OID\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Energy Consumption (Wh) ",
   "type": "timeseries",
   "description": "This graph shows the energy consumption in Watt-hour for VMs in the selected scope and over the selected time. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)\nFROM metric m\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_oid IN (${VM_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Carbon Footprint CO2e (t)",
   "type": "timeseries",
   "description": "This graph shows the carbon footprint in kg of CO2e emissions for VMs in the selected scope and over the selected time. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000 as \"CO2e (t)\"\nFROM metric m\n--JOIN entity e on m.entity_oid = e.\"oid\" AND e.environment = 'ON_PREM' AND e.type = 'VIRTUAL_MACHINE' and m.entity_type = e.type\nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_oid IN (${VM_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  }
 ]
}