{
 "title": "FINOPS - Virtual Machine Cost and Capacity",
 "description": "v 1.0.4",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" },
   {
    "name": "Group",
    "label": "Group Name",
    "query": "SELECT distinct name as __text\n               ,oid as __value\n   from entity\nWhere type = 'GROUP'\nand (first_seen, last_seen) overlaps ($__timeFrom(), $__timeTo())\nand attrs -> 'member_types' ? 'VIRTUAL_MACHINE'"
   },
   { "name": "costvCPU", "label": "Cost Per vCPU", "query": "100" },
   { "name": "costvMEM", "label": "Cost Per GB of Memory", "query": "100" },
   { "name": "costStorage", "label": "Cost Per GB of Storage", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH vms_with_tags AS (\n SELECT DISTINCT ON (e.oid) \n \te.oid AS vm_oid\n  ,s.seed_oid as group_oid\n \t,e.name AS vm_name\n \t,(e.attrs -> 'num_cpus')::int as vcpus\n\n FROM entity e\n   JOIN scope s ON (e.oid = s.scoped_oid)\n WHERE e.type = 'VIRTUAL_MACHINE'\n   AND (s.start, s.finish)overlaps ($__timeFrom(), $__timeTo())\n   AND s.seed_oid in ($Group)\n   )\nselect g.name as \"Group Name\"\n  \n      ,sum(stor_cost) AS \"Cost of Storage\"\n   \n      ,sum(cpu_cost) AS \"Cost of vCPUs\"\n   \n      ,sum(vmem_cost) AS \"Cost of vMem\"\n      ,sum(total_cost) AS \"Total Cost\"\nfrom \n  (SELECT \n    vm_oid,\n    group_oid,\n    avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') as stor_cap,\n    avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') as stor_used,\n    (avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') - avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'))/1024 as stor_free,\n    ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') stor_cost,\n    vcpus,\n    avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU') cpu_cap,\n    avg(metric.current) FILTER (WHERE metric.type = 'VCPU') cpu_used,\n    (avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU')) - (avg(metric.current) FILTER (WHERE metric.type = 'VCPU')) cpu_free,\n    ${costvCPU}*vcpus cpu_cost, \n    avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_cap,\n    avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_used,\n    (avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM')) - (avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM')) vmem_free,\n    ${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_cost,\n    ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED')+${costvCPU}*vcpus+${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') total_cost\n  FROM vms_with_tags\n   JOIN metric ON metric.entity_oid = vm_oid\n  WHERE metric.\"type\" IN ('VMEM', 'VCPU', 'STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n   AND $__timeFilter(metric.\"time\")\n  GROUP BY vm_oid, group_oid, vcpus) as a\njoin entity g on g.oid = a.group_oid\nwhere g.type = 'GROUP'\n and (g.first_seen, g.last_seen) overlaps ($__timeFrom(), $__timeTo())\n and g.oid in ($Group)\n group by 1\n\n\n;"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Group Cost Showback Report",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH vms_with_tags AS (\n SELECT DISTINCT ON (e.oid) \n \te.oid AS vm_oid\n  ,s.seed_oid as group_oid\n \t,e.name AS vm_name\n \t,(e.attrs -> 'num_cpus')::int as vcpus\n\n FROM entity e\n   JOIN scope s ON (e.oid = s.scoped_oid)\n WHERE e.type = 'VIRTUAL_MACHINE'\n   AND (s.start, s.finish)overlaps ($__timeFrom(), $__timeTo())\n   AND s.seed_oid in ($Group)\n   )\nselect g.name as \"Group Name\"\n\n      ,sum(vcpus) AS \"CPU Core #\"\n      ,sum(cpu_cap) AS \"CPU Capacity (Mhz)\"\n      ,sum(cpu_used) AS \"CPU Used (Mhz)\"\n      ,sum(cpu_free) AS \"CPU Free (Mhz)\"\n      ,sum(vmem_cap) AS \"Memory Capacity\"\n      ,sum(vmem_used) AS \"Memory Used\"\n      ,sum(vmem_free) AS \"Memory Free\"\n            ,sum(stor_cap) AS \"Storage Capacity\"\n      ,sum(stor_used) AS \"Storage Used\"\n      ,sum(stor_free) AS \"Storage Free\"\nfrom \n  (SELECT \n    vm_oid,\n    group_oid,\n    avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') as stor_cap,\n    avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') as stor_used,\n    (avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') - avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'))/1024 as stor_free,\n    ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') stor_cost,\n    vcpus,\n    avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU') cpu_cap,\n    avg(metric.current) FILTER (WHERE metric.type = 'VCPU') cpu_used,\n    (avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU')) - (avg(metric.current) FILTER (WHERE metric.type = 'VCPU')) cpu_free,\n    ${costvCPU}*vcpus cpu_cost, \n    avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_cap,\n    avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_used,\n    (avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM')) - (avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM')) vmem_free,\n    ${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_cost,\n    ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED')+${costvCPU}*vcpus+${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') total_cost\n  FROM vms_with_tags\n   JOIN metric ON metric.entity_oid = vm_oid\n  WHERE metric.\"type\" IN ('VMEM', 'VCPU', 'STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n   AND $__timeFilter(metric.\"time\")\n  GROUP BY vm_oid, group_oid, vcpus) as a\njoin entity g on g.oid = a.group_oid\nwhere g.type = 'GROUP'\n and (g.first_seen, g.last_seen) overlaps ($__timeFrom(), $__timeTo())\n and g.oid in ($Group)\n group by 1\n\n\n;"
    }
   ]
  },
  {
   "title": "Virtual Machine Cost Showback Chart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH vms_with_tags AS (\n SELECT DISTINCT ON (e.oid) \n \te.oid AS vm_oid\n \t,e.name AS vm_name\n \t,(e.attrs -> 'num_cpus')::int as vcpus\n\n FROM entity e\n   JOIN scope s ON (e.oid = s.scoped_oid)\n WHERE e.type = 'VIRTUAL_MACHINE'\n   AND (s.start, s.finish) OVERLAPS (now() - interval '10 minute', now())\n   AND s.seed_oid in ($Group)\n   )\n   \nSELECT \n vm_name AS \"VM name\",\n avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Storage Capacity\",\n avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Storage Used\",\n (avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') - avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'))/1024 AS \"Storage Free\",\n ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Cost of Storage\",\n vcpus AS \"CPU Cores #\",\n avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU') AS \"CPU Capacity (Mhz)\",\n avg(metric.current) FILTER (WHERE metric.type = 'VCPU') AS \"CPU Used (Mhz)\",\n (avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU')) - (avg(metric.current) FILTER (WHERE metric.type = 'VCPU')) AS \"CPU Free (Mhz)\",\n ${costvCPU}*vcpus AS \"Cost of vCPUs\", \n avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Memory Capacity\",\n avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Memory Used\",\n (avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM')) - (avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM')) AS \"Memory Free\",\n ${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Cost of vMem\",\n ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED')+${costvCPU}*vcpus+${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Total Cost\"\nFROM vms_with_tags\nJOIN metric ON metric.entity_oid = vm_oid\nWHERE metric.\"type\" IN ('VMEM', 'VCPU', 'STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n AND metric.\"time\" BETWEEN now() - interval '10 minute' and now()\nGROUP BY vm_name, vm_oid, vcpus\nORDER BY \"CPU Cores #\" desc;"
    }
   ]
  },
  {
   "title": "Group Cost Showback Report",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH vms_with_tags AS (\n SELECT DISTINCT ON (e.oid) \n \te.oid AS vm_oid\n  ,s.seed_oid as group_oid\n \t,e.name AS vm_name\n \t,(e.attrs -> 'num_cpus')::int as vcpus\n\n FROM entity e\n   JOIN scope s ON (e.oid = s.scoped_oid)\n WHERE e.type = 'VIRTUAL_MACHINE'\n   AND (s.start, s.finish)overlaps ($__timeFrom(), $__timeTo())\n   AND s.seed_oid in ($Group)\n   )\nselect g.name as \"Group Name\"\n      ,sum(total_cost) AS \"Total Cost\"\n      ,sum(cpu_cost) AS \"Cost of vCPUs\"\n            ,sum(vmem_cost) AS \"Cost of vMem\"\n      ,sum(stor_cost) AS \"Cost of Storage\"\n\n\n      ,sum(stor_cap) AS \"Storage Capacity\"\n      ,sum(stor_used) AS \"Storage Used\"\n      ,sum(stor_free) AS \"Storage Free\"\n\n      ,sum(vcpus) AS \"CPU Core #\"\n      ,sum(cpu_cap) AS \"CPU Capacity (Mhz)\"\n      ,sum(cpu_used) AS \"CPU Used (Mhz)\"\n      ,sum(cpu_free) AS \"CPU Free (Mhz)\"\n\n      ,sum(vmem_cap) AS \"Memory Capacity\"\n      ,sum(vmem_used) AS \"Memory Used\"\n      ,sum(vmem_free) AS \"Memory Free\"\n\nfrom \n  (SELECT \n    vm_oid,\n    group_oid,\n    avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') as stor_cap,\n    avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') as stor_used,\n    (avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') - avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'))/1024 as stor_free,\n    ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') stor_cost,\n    vcpus,\n    avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU') cpu_cap,\n    avg(metric.current) FILTER (WHERE metric.type = 'VCPU') cpu_used,\n    (avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU')) - (avg(metric.current) FILTER (WHERE metric.type = 'VCPU')) cpu_free,\n    ${costvCPU}*vcpus cpu_cost, \n    avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_cap,\n    avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_used,\n    (avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM')) - (avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM')) vmem_free,\n    ${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') vmem_cost,\n    ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED')+${costvCPU}*vcpus+${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') total_cost\n  FROM vms_with_tags\n   JOIN metric ON metric.entity_oid = vm_oid\n  WHERE metric.\"type\" IN ('VMEM', 'VCPU', 'STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n   AND $__timeFilter(metric.\"time\")\n  GROUP BY vm_oid, group_oid, vcpus) as a\njoin entity g on g.oid = a.group_oid\nwhere g.type = 'GROUP'\n and (g.first_seen, g.last_seen) overlaps ($__timeFrom(), $__timeTo())\n and g.oid in ($Group)\n group by 1\n\n\n;"
    }
   ]
  },
  {
   "title": "VM Cost Showback Report",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH vms_with_tags AS (\n SELECT DISTINCT ON (e.oid) \n \te.oid AS vm_oid\n \t,e.name AS vm_name\n \t,(e.attrs -> 'num_cpus')::int as vcpus\n\n FROM entity e\n   JOIN scope s ON (e.oid = s.scoped_oid)\n WHERE e.type = 'VIRTUAL_MACHINE'\n   AND (s.start, s.finish) OVERLAPS (now() - interval '10 minute', now())\n   AND s.seed_oid in ($Group)\n   )\n   \nSELECT \n vm_name AS \"VM name\",\n avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Storage Capacity\",\n avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_AMOUNT') AS \"Storage Used\",\n (avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') - avg(metric.consumed) FILTER (WHERE metric.type = 'STORAGE_AMOUNT'))/1024 AS \"Storage Free\",\n ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED') AS \"Cost of Storage\",\n vcpus AS \"CPU Core #\",\n avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU') AS \"CPU Capacity (Mhz)\",\n avg(metric.current) FILTER (WHERE metric.type = 'VCPU') AS \"CPU Used (Mhz)\",\n (avg(metric.capacity) FILTER (WHERE metric.type = 'VCPU')) - (avg(metric.current) FILTER (WHERE metric.type = 'VCPU')) AS \"CPU Free (Mhz)\",\n ${costvCPU}*vcpus AS \"Cost of vCPUs\", \n avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Memory Capacity\",\n avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Memory Used\",\n (avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM')) - (avg(metric.current/1024/1024) FILTER (WHERE metric.type = 'VMEM')) AS \"Memory Free\",\n ${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Cost of vMem\",\n ${costStorage}*avg(metric.consumed/1024) FILTER (WHERE metric.type = 'STORAGE_PROVISIONED')+${costvCPU}*vcpus+${costvMEM}*avg(metric.capacity/1024/1024) FILTER (WHERE metric.type = 'VMEM') AS \"Total Cost\"\nFROM vms_with_tags\nJOIN metric ON metric.entity_oid = vm_oid\nWHERE metric.\"type\" IN ('VMEM', 'VCPU', 'STORAGE_AMOUNT', 'STORAGE_PROVISIONED')\n AND metric.\"time\" BETWEEN now() - interval '10 minute' and now()\nGROUP BY vm_name, vm_oid, vcpus\nORDER BY \"CPU Core #\" desc;"
    }
   ]
  }
 ]
}