{
 "title": "Sustainable IT Dashboard",
 "description": "Sustainable IT Dashboard ",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DATACENTER",
    "label": "Data Center",
    "query": "select distinct\n    name AS __text,\n    oid AS __value\nfrom entity\nwhere\n    type = 'DATACENTER'\n    and attrs->>'targets' like '%vCenter%'\n    and last_seen > now()\norder by 1"
   },
   {
    "name": "CLUSTER",
    "label": "Cluster",
    "query": "select distinct\n    e.name AS __text,\n    e.oid AS __value\nfrom \"scope\" s \njoin entity e on s.scoped_oid = e.\"oid\"\nwhere\n    s.scoped_type = 'COMPUTE_CLUSTER'\n    and s.seed_oid IN (${DATACENTER})\n    and e.last_seen > now()\norder by 1"
   },
   {
    "name": "HOST_LIST",
    "label": "Host List",
    "query": "select distinct\n    e.name AS __text,\n    e.oid AS __value\nfrom \"scope\" s \njoin entity e on s.scoped_oid = e.\"oid\"\nwhere\n    s.scoped_type = 'VIRTUAL_MACHINE'\n\n    and e.last_seen > now()\n\norder by 1"
   },
   { "name": "PRIVATE_CLOUD_AVG_PUE", "label": "PUE", "query": "1.67" },
   { "name": "PRIVATE_CLOUD_EMISSIONS_FACTOR", "label": "Emissions Factor", "query": "0.000709" },
   { "name": "PERCENT_RENEWABLE_ENERGY", "label": "% Renewable Energy", "query": "0" },
   {
    "name": "TREE_SEQUESTRATION_FACTOR",
    "query": "${VAR_TREE_SEQUESTRATION_FACTOR}"
   },
   {
    "name": "ACRES_OF_FOREST_SEQUESTRATION_FACTOR",
    "query": "${VAR_ACRES_OF_FOREST_SEQUESTRATION_FACTOR}"
   },
   {
    "name": "VEHICLE_EMISSIONS_FACTOR",
    "query": "${VAR_VEHICLE_EMISSIONS_FACTOR}"
   },
   {
    "name": "HOUSEHOLD_EMISSIONS_FACTOR",
    "query": "${VAR_HOUSEHOLD_EMISSIONS_FACTOR}"
   },
   { "name": "AWS_MIN_CONSUMPTION", "query": "${VAR_AWS_MIN_CONSUMPTION}" },
   { "name": "AWS_MAX_CONSUMPTION", "query": "${VAR_AWS_MAX_CONSUMPTION}" },
   { "name": "AZURE_MIN_CONSUMPTION", "query": "${VAR_AZURE_MIN_CONSUMPTION}" },
   { "name": "AZURE_MAX_CONSUMPTION", "query": "${VAR_AZURE_MAX_CONSUMPTION}" },
   { "name": "GCP_MIN_CONSUMPTION", "query": "${VAR_GCP_MIN_CONSUMPTION}" },
   { "name": "GCP_MAX_CONSUMPTION", "query": "${VAR_GCP_MAX_CONSUMPTION}" },
   { "name": "CPU_CONSUMPTION", "label": "CPU_CONSUMPTION", "query": "300" },
   { "name": "CORES_CPU", "label": "CORES PER CPU", "query": "8" },
   { "name": "W_WH_RATIO", "query": "0.166" },
   { "name": "EFFICIENCY", "label": "EFFICIENCY", "query": "1" }
  ]
 },
 "panels": [
  { "title": "🌏 Impact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "💻 Active CPUs",
   "type": "stat",
   "description": "How many acres of forest per year will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*count(e.name)/${CORES_CPU} as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "⚡ Average Energy Consumption (Wh/year) - All VMs",
   "type": "stat",
   "description": "How many acres of forest per year will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY}*24*365 as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "⛽ Average CO2e Emissions (t/year) - All VMs",
   "type": "stat",
   "description": "How many acres of forest per year will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY}*${PRIVATE_CLOUD_AVG_PUE}/1000*${PRIVATE_CLOUD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100*24*365 as \"CO2e (t)\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nGROUP BY m.time\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "# Sustainability Dashboard\n\nThis dashboard shows the impact of IBM Turbonomic application resource manager on Energy consumption and Carbon Dioxide equivalents (CO2e) emissions in your private cloud data center environment.\n\n"
   }
  },
  {
   "title": "🦌 Total CO2e emissions - Equivalent in acres of forest per year",
   "type": "stat",
   "description": "How many acres of forest per year will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "acre" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*count(e.name)/${CORES_CPU}*${CPU_CONSUMPTION}*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000/${ACRES_OF_FOREST_SEQUESTRATION_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100 as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "🌲Total CO2e emissions - Equivalent in trees growing for 10 years",
   "type": "stat",
   "description": "How many trees growing for 10 years will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "trees" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*count(e.name)/${CORES_CPU}*${CPU_CONSUMPTION}*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000/${TREE_SEQUESTRATION_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100 as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "🚗 Total CO2e emissions - Vehicles per year ",
   "type": "stat",
   "description": "The amount of total CO2e emissions released by physical machines in the selected scope and over the selected time is equivalent to the amount of CO2e emissions released by vehicles driven for 1 year. ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*count(e.name)/${CORES_CPU}*${CPU_CONSUMPTION}*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000/${VEHICLE_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100 as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "🏠 Total CO2e emissions - Household per year",
   "type": "stat",
   "description": "The amount of total CO2e emissions released by physical machines in the selected scope and over the selected time is equivalent to the amount of CO2e emissions released by household electricity consumption for 1 year. ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*count(e.name)/${CORES_CPU}*${CPU_CONSUMPTION}*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}/1000/${HOUSEHOLD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100 as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Energy Consumption (Wh) - All VMs",
     "type": "stat",
     "description": "How many acres of forest per year will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY} as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nGROUP BY m.time\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Average CO2e Emissions per hour - All VMs",
     "type": "stat",
     "description": "How many acres of forest per year will it take to sequester the total CO2e emissions released by physical machines in the selected scope and over the selected time. ",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY}*${PRIVATE_CLOUD_AVG_PUE}/1000*${PRIVATE_CLOUD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100*1000 as \"CO2e (kg)\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nGROUP BY m.time\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Energy Consumption (Wh) - All VMs",
     "type": "timeseries",
     "description": "Total energy consumption in Watt-Hour of all hosts in the selected scope and during the selected time of the dashboard. ",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY} as value\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nGROUP BY m.time\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CO2e Emissions (t) - All VMs",
     "type": "timeseries",
     "description": "CO2e emissions graph shows the CO2e emissions in metric tons (1 metric ton = 1,000Kg) for the hosts in the selected scope and over the selected period of the dashboard. \nCO2e emissions are calculated using Cloud Carbon Footprint open source methodology. See the Help section for more details. ",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  sum(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY}*${PRIVATE_CLOUD_AVG_PUE}/1000*${PRIVATE_CLOUD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100*1000 as \"CO2e (kg)\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nGROUP BY m.time\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Average Energy per VM (Wh)",
     "type": "timeseries",
     "description": "Estimated average energy per active VMs in the selected scope.\nActive - powered on and discovered by Turbonomic.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  SUM(m.current)*${CPU_CONSUMPTION} as \"Total Hosts Energy\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.type = 'VCPU'\nGROUP BY m.time\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  count(m.utilization) as \"Number of Active VMs\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\njoin scope s on m.entity_oid = s.scoped_oid and s.finish > now() and s.scoped_type = 'VIRTUAL_MACHINE'\nWHERE\n  $__timeFilter(time) and\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.type = 'VCPU' \nGROUP BY m.time\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Number of Active VM(s)",
     "type": "stat",
     "description": "This chart shows the number of active VMs in your on-prem environment, and tracks the data over the selected period. \nActive VMs - powered on and discovered by Turbonomic.",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  count(e.name) as \"Number of VMs\"\nFROM entity e\nWHERE\n  e.type = 'VIRTUAL_MACHINE' \n"
      }
     ]
    },
    {
     "title": "Active VMs",
     "type": "timeseries",
     "description": "This graph shows the ration of number of active VMs per host over the selected period of the dashboard. \nActive VMs - powered on and discovered by Turbonomic.",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 33 },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  count(m.utilization) as \"Number of Active VMs\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\njoin scope s on m.entity_oid = s.scoped_oid and s.finish > now() and s.scoped_type = 'VIRTUAL_MACHINE'\nWHERE\n  $__timeFilter(time) and\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.type = 'VCPU' AND\n  s.seed_oid IN (${HOST_LIST})\nGROUP BY m.time\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Individual Host Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Power Consumption (W) - Individual VM(s)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 6 }
     ]
    },
    {
     "title": "Average Energy Consumption (Wh) - Individual VM(s)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 48 }
     ]
    },
    {
     "title": "Power Consumption (W) - Individual VM(s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.current/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${EFFICIENCY} as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nORDER BY 1, 3"
      }
     ]
    },
    {
     "title": "Energy Consumption (Wh) - Individual VM(s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  m.current/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${W_WH_RATIO}*${EFFICIENCY} as value,\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.provider_oid is null AND\n  m.type = 'VCPU' AND\n  m.current>0\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CO2e Emissions (t) - Individual VM(s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "masst" } },
     "targets": [
      {
       "rawSql": "SELECT\n  m.\"time\" as \"time\",\n  (m.current)/1000*${CPU_CONSUMPTION}*${PRIVATE_CLOUD_AVG_PUE}/1000*${PRIVATE_CLOUD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100 as \"MTCO2e\",\n  e.name as metric\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\" \nWHERE\n  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU' AND\n  m.current>0\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Optimization Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Suspend Actions - Estimated Missed Energy and CO2e Savings",
     "type": "stat",
     "description": "Estimated average energy savings from all Turbonomic suspend actions. \nEstimated energy savings are calculated based on the average energy over the selected time period for each one of the hosts that have a suspend action attached to them ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    },
    {
     "title": "VM Suspend Actions",
     "type": "table",
     "description": "List of all Host Suspend actions in the selected scope. \nAverage Energy = average energy consumption of the host over the selected period of the report (for example over last 3 hours)\nEstimated Yearly Average = the average energy multiplied by the number of hours in a year to get the average annual energy in W-h. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "rawSql": "SELECT\n  DISTINCT ON (e.\"name\") \n  TO_CHAR(a.recommendation_time, 'dd/mm/yyyy hh:mm:ss') as \"Date Recommended\",\n   e.\"name\" as \"Host Name\",\n  e.\"oid\" as \"Host OID\",\n  a.description as \"Description\",\n  a.target_entity_id as \"ID\"\nFROM pending_action a\nJOIN entity e on e.oid = a.target_entity_id\njoin scope s on s.scoped_oid = e.oid  and s.finish > now()\nwhere\n--  $__timeFilter(a.recommendation_time) AND\n  a.\"type\" = 'DEACTIVATE'  AND\n  e.\"type\" = 'VIRTUAL_MACHINE'  AND\n  a.target_entity_id IN (${HOST_LIST})\nORDER BY \"Host Name\"\n"
      },
      {
       "rawSql": "SELECT\n  e.oid as \"Host OID\",\n  avg(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${EFFICIENCY} as \"Energy Avg (Wh)\",\n  (avg(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${EFFICIENCY}*365*24) as \"Estimated Yearly Energy Avg (Wh)\",\n  avg(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${EFFICIENCY}*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100 as \"CO2e Avg (kg)\",\n  avg(m.current)/1000*${CPU_CONSUMPTION}/${CORES_CPU}*${EFFICIENCY}*${PRIVATE_CLOUD_AVG_PUE}*${PRIVATE_CLOUD_EMISSIONS_FACTOR}*(100-${PERCENT_RENEWABLE_ENERGY})/100*24*365/1000 as \"Estimated Yearly CO2e Avg (t)\"\nFROM metric m\nJOIN entity e on m.entity_oid = e.\"oid\"\nJOIN pending_action pa on pa.target_entity_id = e.oid\nWHERE\n--  $__timeFilter(m.\"time\") AND\n  m.entity_type = 'VIRTUAL_MACHINE' AND\n  m.entity_oid IN (${HOST_LIST}) AND\n  m.type = 'VCPU'\nGROUP BY e.oid\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readme",
     "type": "text",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 21 },
     "options": {
      "content": "# Sustainable IT Dashboard\n***\n## Summary\nThis dashboard shows the impact of IBM Turbonomic application resource manager on Energy consumption and Carbon Dioxide equivalents (CO2e) emissions in your private cloud data center environment. \n\nThis dashboard focuses on data collected for physical machines (hosts) through a vCenter API and includes energy consumption data, number of hosts and VMs, VM-to-Host density ratios as well as the number and the type of generated host suspend and provision actions.\n***\n\n## Data and Methodology\n\n**Energy (Wh)** - data is collected from vCenter API and summed over a period of 10 minutes to get a single number for total Energy (Wh) in 10 minutes. \n\n**CO2e emissions (t)** - carbon emissions calculations are made following an open source methodology outlined in Cloud Carbon Footprint website - [www.cloudcarbonfootprint.org](https://www.cloudcarbonfootprint.org/).    \nSpecifically, in this dashboard carbon emissions are calculated using the following formula:\n\n    Operational Emissions = CO2e (t) = (energy consumption [Wh]) x ((private cloud average PUE) / 1000) x (private cloud emissions factor) x ((100 - percent renewable energy) / 100)\n\nWhere:\n\n- ***Private Cloud Power Usage Effectiveness (PUE)*** = An average PUE of 1.67 is used in our calculations. This [451 report](https://d39w7f4ix9f5s9.cloudfront.net/e3/79/42bf75c94c279c67d777f002051f/carbon-reduction-opportunity-of-moving-to-aws.pdf) notes: \"Adding it all up, the power usage effectiveness (PUE, the ratio of total datacenter power and the IT power) ranged from 1.63 to 1.70 in the survey sample and was consistent across company sizes. This is in line with broader industry data collected by the Uptime Institute but well below the efficiency of AWS operations.\" - 451 Research Report. We use the average of 1.63 and 1.70, which is 1.67.\n\n- ***Private Cloud Emissions Factor*** = `1,562.4 lbs CO2/MWh × (4.536 × 10^(-4) metric tons/lb) × 0.001 MWh/kWh = 7.09 × 10^(-4) metric tons CO2/kWh`. We are using `0.000709` (rounded) in our calculations. ***Note:*** Emission equivalents vary slightly vs. EPA calculation because we are using the rounded numbers of the emissions factor (7.09x10^(-4)).\n\n- ***Percent Renewable Energy*** = User can input the percent renewable energy that is used to generate the energy that is used by the datacenter in which physical hosts that are shown in this dashboard reside. CO2e emissions calculations will be adjusted by this input. \n\n**Density** - this chart shows the number of active VMs per host in your on-prem environment, and tracks the data over the selected dashboard time. \n\n**Estimated carbon sequestration equivalents** - real world examples of sequestration efforts to remove the total CO2e emissions reported in the *\"CO2e Emissions (t) - All Hosts\"* chart. ***Note:*** All sequestration equivalents and carbon emissions equivalents are adjusted for percent renewable energy inserted at the top of the dashboard.    \nSequestration formulas are as follow:\n\n- ***Equivalent Carbon Sequestered by Acres of Forest in 1 year (metric tons CO2 / acre)*** = Total Emissions (metric tons CO2) * Acres of Forest Sequestration Factor.    \nWhere:    \nAcres of Forest Sequestration Factor = -0.23 metric ton C/acre/year* × (44 units CO2/12 units C) = -0.84 metric ton CO2/acre/year sequestered annually by one acre of average U.S. forest.\n\n- ***Equivalent Carbon Sequestered by Tree Seedlings Grown for 10 years (metric ton CO2 / tree)*** = Total Emissions (metric tons CO2) * Tree Sequestration Factor.    \nWhere:    \nTree Sequestration Factor = (-36.4 lbs C/tree × (44 units CO2/12 units C) × 1 metric ton/2,204.6 lbs) = -0.060 metric ton CO2 per urban tree planted.\n\n**Carbon Emissions Equivalents** - To calculate the carbon emission equivalencies we use the formulas provided by United States EPA Greenhouse Gas Equivalencies Calculator [here](https://www.epa.gov/energy/greenhouse-gases-equivalencies-calculator-calculations-and-references). Please note that there will be slight variation between the results you see in the dashboard and what is calculated by the EPA’s site because we are using the numbers they have published, which they have rounded.\n- ***Equivalent Passenger Vehicles*** = Total Emissions (metric tons CO2) * Passenger Vehicles Factor (metric tons CO2e/vehicles/year).    \nWhere:    \nPassenger Vehicles Factor (vehicles/year) = 8.89 × (10^-3) metric tons CO2/gallon gasoline × 11,556 VMT car/truck average × 1/22.5 miles per gallon car/truck average × 1 CO2, CH4, and N2O/0.993 CO2 = 4.60 metric tons CO2e/vehicle/year.\n\n- ***Equivalent Home Electricity Use*** - Total Emissions (metric tons CO2) * Home Electricity Use Factor.   \nWhere:    \nHome Electricity Use Facto r= 11,880 kWh per home × 947.2 lbs CO2 per megawatt-hour generated × 1/(1-0.073) MWh delivered/MWh generated × 1 MWh/1,000 kWh × 1 metric ton/2,204.6 lb = 5.505 metric tons CO2/home.\n"
     }
    }
   ]
  }
 ]
}