apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret-upi04
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: UPI_04
  server: https://api.ocp-270003bu3k-xxxx.cloud.techzone.ibm.com:6443
  config: |
    {
      "bearerToken": "sha256~xxxxxxx",
      "tlsClientConfig": {
        "insecure": false
      }
    }