{
 "title": "Applications Performance",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "APPLICATION_NAME",
    "label": "Application",
    "query": "select e.name from entity e where e.\"type\" = 'BUSINESS_APPLICATION' order by e.name"
   },
   {
    "name": "APPLICATION_OID",
    "label": "Application OID",
    "query": "select e.oid from entity e where e.\"type\" = 'BUSINESS_APPLICATION' and e.name IN ('${APPLICATION_NAME}')"
   },
   { "name": "INCLUDE_NEIGHBORS", "label": "Include Neighbor Entities", "query": "Yes,No" }
  ]
 },
 "panels": [
  {
   "title": "Pending Actions Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Pending Actions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(recommendation_time, 'dd/mm/yyyy hh:mm:ss') AS \"Recommendation Time\",\n  e.name as \"Component Name\",\n  --e.type as \"type\",\n  CASE pa.category\n    WHEN 'PERFORMANCE_ASSURANCE' THEN 'Performance Assurance'\n    WHEN 'PREVENTION' THEN 'Prevention'\n    WHEN 'EFFICIENCY_IMPROVEMENT' THEN 'Efficiency Improvement'\n    WHEN 'COMPLIANCE' THEN 'Compliance' END as \"Category\",\n  pa.\"type\" as \"Type\",\n  pa.description AS \"Description\"\nFROM pending_action pa\nJOIN entity e ON e.oid = pa.target_entity_id\nWHERE\n  pa.target_entity_id IN\n  (\n    SELECT\n      DISTINCT s.scoped_oid\n    FROM scope s\n    --JOIN entity e ON s.scoped_oid = e.oid\n    WHERE\n      s.seed_oid IN (${APPLICATION_OID})\n    --AND e.type <> 'GROUP'\n    AND s.finish > now()\n  )\nORDER BY 1 DESC"
    },
    {
     "rawSql": "SELECT\n  TO_CHAR(recommendation_time, 'dd/mm/yyyy hh:mm:ss') AS \"Recommendation Time\",\n  e.name as \"Component Name\",\n  --e.type as \"type\",\n  CASE pa.category\n    WHEN 'PERFORMANCE_ASSURANCE' THEN 'Performance Assurance'\n    WHEN 'PREVENTION' THEN 'Prevention'\n    WHEN 'EFFICIENCY_IMPROVEMENT' THEN 'Efficiency Improvement'\n    WHEN 'COMPLIANCE' THEN 'Compliance' END as \"Category\",\n  pa.\"type\" as \"Type\",\n  pa.description AS \"Description\"\nFROM pending_action pa\nJOIN entity e ON e.oid = pa.target_entity_id\nWHERE\n  pa.target_entity_id IN\n  (\n    select s.scoped_oid\n    from \"scope\" s \n    where s.seed_oid in (\n      select s.scoped_oid\n\t    from \"scope\" s \n\t    where s.scoped_type = 'PHYSICAL_MACHINE'\n\t    and s.seed_oid IN (${APPLICATION_OID})\n\t    and s.finish > now()\n\t  )\n  and s.scoped_type = 'VIRTUAL_MACHINE'\n  and s.finish > now()\n  )\nAND pa.type IN ('MOVE', 'PROVISION', 'SUSPEND')\nAND ('${INCLUDE_NEIGHBORS}' = 'Yes')\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Executed Actions Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "title": "Executed Actions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(recommendation_time, 'dd/mm/yyyy hh:mm:ss') AS \"Recommendation Time\",\n  e.name as \"Component Name\",\n  --e.type as \"type\",\n  CASE ca.category\n    WHEN 'PERFORMANCE_ASSURANCE' THEN 'Performance Assurance'\n    WHEN 'PREVENTION' THEN 'Prevention'\n    WHEN 'EFFICIENCY_IMPROVEMENT' THEN 'Efficiency Improvement'\n    WHEN 'COMPLIANCE' THEN 'Compliance' END as \"Category\",\n  ca.\"type\" as \"Type\",\n  ca.description AS \"Description\",\n  ca.final_state AS \"Final State\"\nFROM completed_action ca\nJOIN entity e ON e.oid = ca.target_entity_id\nWHERE\n  ca.target_entity_id IN\n  (\n    SELECT\n      DISTINCT s.scoped_oid\n    FROM scope s\n    --JOIN entity e ON s.scoped_oid = e.oid\n    WHERE\n      s.seed_oid IN (${APPLICATION_OID})\n    --AND e.type <> 'GROUP'\n    AND s.finish > now()\n  )\nORDER BY 1 DESC"
    },
    {
     "rawSql": "SELECT\n  TO_CHAR(recommendation_time, 'dd/mm/yyyy hh:mm:ss') AS \"Recommendation Time\",\n  e.name as \"Component Name\",\n  --e.type as \"type\",\n  CASE ca.category\n    WHEN 'PERFORMANCE_ASSURANCE' THEN 'Performance Assurance'\n    WHEN 'PREVENTION' THEN 'Prevention'\n    WHEN 'EFFICIENCY_IMPROVEMENT' THEN 'Efficiency Improvement'\n    WHEN 'COMPLIANCE' THEN 'Compliance' END as \"Category\",\n  ca.\"type\" as \"Type\",\n  ca.description AS \"Description\",\n  ca.final_state AS \"Final State\"\nFROM completed_action ca\nJOIN entity e ON e.oid = ca.target_entity_id\nWHERE\n  ca.target_entity_id IN\n  (\n    select s.scoped_oid\n    from \"scope\" s \n    where s.seed_oid in (\n      select s.scoped_oid\n\t    from \"scope\" s \n\t    where s.scoped_type = 'PHYSICAL_MACHINE'\n\t    and s.seed_oid IN (${APPLICATION_OID})\n\t    and s.finish > now()\n\t  )\n  and s.scoped_type = 'VIRTUAL_MACHINE'\n  and s.finish > now()\n  )\nAND ca.type IN ('MOVE', 'PROVISION', 'SUSPEND')\nAND ('${INCLUDE_NEIGHBORS}' = 'Yes')\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Response Time & Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms", "label": "response time" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  CASE \"type\"::text\n    WHEN 'RESPONSE_TIME' THEN 'Response Time'\n    WHEN 'TRANSACTION' THEN 'Transaction(s)' END as \"metric\",\n  current as \"value\"\nFROM metric m\nWHERE\n  $__timeFilter(time)\n  AND entity_oid in ('${APPLICATION_OID}')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Business Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Business Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.name as \"Component Name\"\n  --e.\"type\" as \"Component Type\",\n  --TO_CHAR(s.start, 'dd/mm/yyyy hh:mm:ss') as \"Start Time\",\n  --TO_CHAR(s.finish, 'dd/mm/yyyy hh:mm:ss') as \"Finish Time\"\nFROM scope s\nJOIN entity e ON s.scoped_oid = e.oid\nWHERE\n  (s.start, s.finish) overlaps ($__timeFrom(), $__timeTo())\n  AND s.seed_oid IN (${APPLICATION_OID})\n  AND e.type <> 'GROUP'\n  AND e.type = 'BUSINESS_TRANSACTION'\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.name as \"Component Name\"\n  --e.\"type\" as \"Component Type\",\n  --TO_CHAR(s.start, 'dd/mm/yyyy hh:mm:ss') as \"Start Time\",\n  --TO_CHAR(s.finish, 'dd/mm/yyyy hh:mm:ss') as \"Finish Time\"\nFROM scope s\nJOIN entity e ON s.scoped_oid = e.oid\nWHERE\n  (s.start, s.finish) overlaps ($__timeFrom(), $__timeTo())\n  AND s.seed_oid IN (${APPLICATION_OID})\n  AND e.type <> 'GROUP'\n  AND e.type = 'SERVICE'\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Application Components",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Application Components",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.name as \"Component Name\"\n  --e.\"type\" as \"Component Type\",\n  --TO_CHAR(s.start, 'dd/mm/yyyy hh:mm:ss') as \"Start Time\",\n  --TO_CHAR(s.finish, 'dd/mm/yyyy hh:mm:ss') as \"Finish Time\"\nFROM scope s\nJOIN entity e ON s.scoped_oid = e.oid\nWHERE\n  (s.start, s.finish) overlaps ($__timeFrom(), $__timeTo())\n  AND s.seed_oid IN (${APPLICATION_OID})\n  AND e.type <> 'GROUP'\n  AND e.type = 'APPLICATION_COMPONENT'\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Detailed Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  DISTINCT e.name as \"Component Name\",\n  e.\"type\" as \"Component Type\",\n  TO_CHAR(s.start, 'dd/mm/yyyy hh:mm:ss') as \"Start Time\",\n  TO_CHAR(s.finish, 'dd/mm/yyyy hh:mm:ss') as \"Finish Time\"\nFROM scope s\nJOIN entity e ON s.scoped_oid = e.oid\nWHERE\n  (s.start, s.finish) overlaps ($__timeFrom(), $__timeTo())\n  AND s.seed_oid IN (${APPLICATION_OID})\n  AND e.type <> 'GROUP'\nORDER BY 2 ASC"
    }
   ]
  }
 ]
}