apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple
  namespace: openshift-gitops
spec:
  destination:
    namespace: ibm-aiops-installer
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: tools/97_addons/experimental/gitops/content/cp4aiops-demo-content
    repoURL: 'https://github.com/niklaushirt/ibm-aiops-deployer'
    targetRevision: dev_latest
