
  global:
    ingress:
      secrets:   
        - certificate: |
            -----BEGIN CERTIFICATE-----
            xxx
            -----END CERTIFICATE-----
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            xxx
            -----END RSA PRIVATE KEY-----
          name: nginx-ingressgateway-certs
                      



