apiVersion: v1
kind: Namespace
metadata:
  name: awx
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
  annotations:
    openshift.io/sa.scc.mcs: 's0:c30,c0'
    openshift.io/sa.scc.supplemental-groups: 1000870000/10000
    openshift.io/sa.scc.uid-range: 1000870000/10000
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: awx-xwqwm
  namespace: awx
spec:
  targetNamespaces:
    - awx
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: awx-operator
  namespace: awx
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: awx-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: awx-operator.v2.8.0


  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
  annotations:
    openshift.io/sa.scc.mcs: 's0:c30,c0'
    openshift.io/sa.scc.supplemental-groups: 1000870000/10000
    openshift.io/sa.scc.uid-range: 1000870000/10000
