spec:
  template:
    spec:
      containers:
      - name: aiops-topology-layout
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 7085
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 30
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 7085
            scheme: HTTPS
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 60


spec:
  template:
    spec:
      containers:
      - name: metric-action
        readinessProbe:
          exec:
            command:
              - sh
              - '-c'
              - >-
                echo "Execuecting command for readness props..." && ls
                /opt/app/lib/noi-metric-action-service*
          initialDelaySeconds: 1
          timeoutSeconds: 10
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 30
        livenessProbe:
          exec:
            command:
              - /opt/app/liveness.sh
          initialDelaySeconds: 1
          timeoutSeconds: 30
          periodSeconds: 50
          successThreshold: 1
          failureThreshold: 1