spec:
  template:
    spec:
      containers:
      - name: aiops-topology-inventory
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 9179
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 30
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 9179
            scheme: HTTPS
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 60


